<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Introduction to Boosting

_Authors: Kiefer Katovich (SF), Matt Brems (DC)_

---

### Learning Objectives

- Understand the differences between bagging and boosting.
- Understand how boosting is an ensemble method.
- Learn the pros and cons to using boosting models.
- Learn the effect of boosting on the bias-variance trade-off.
- Learn the math and procedure for AdaBoost, the "classic" boosting model.
- Understand the differences between AdaBoost and gradient-boosting models.

### Lesson Guide

- [Boosting as an Ensemble Method](#intro)
- [Pros and Cons of Boosting](#pros-cons)
- [A Visual Description of Bagging vs. Boosting](#viz)
- [Boosting and the Bias-Variance Trade-Off](#bias-variance)
- [AdaBoost](#adaboost)
    - [Training Example: Weights](#ex-weights)
- [AdaBoost Visualization](#adaboost-viz)
- [Gradient Boosting Models](#gradient)
- [Gradient Boosting Visualization](#gboost-viz)
- [The difference Between AdaBoost and Gradient Boosting](#the-difference-between-the-adaboost-and-gradient-boosting)
- [Additional Resources](#resources)

<a id='intro'></a>

## Boosting as an Ensemble Method

---

Boosting is another ensemble method with a different approach to bagging. Boosting takes a weak base learner and tries to make it a strong learner by retraining it on the misclassified samples.

1) **Base model fitting is an iterative procedure**: It cannot be run in parallel.
- **Weights are assigned to observations to indicate their "importance:"** Samples with higher weights are given higher influence on the total error of the next model, prioritizing those observations.
- **Weights change at each iteration with the goal of correcting the errors/misclassifications of the previous iteration**: The first base estimator is fit with uniform weights on the observations.
- **Final prediction is typically constructed by a weighted vote**: Weights for each base model depend on their training errors or misclassification rates.

<a id='pros-cons'></a>
## Pros and Cons of Boosting

---

### Pros

- Achieves higher performance than bagging when the hyperparameters are properly tuned.
- Works equally well for classification and regression.
- Can use "robust" loss functions that make the model resistant to outliers.

---

### Cons

- Difficult and time consuming to properly tune hyperparameters.
- Cannot be parallelized like bagging (bad scalability when there are huge amounts of data).
- Higher risk of overfitting compared to bagging.

<a id='viz'></a>
![boostvsbag](./images/BoostingVSBagging.png)

<a id='bias-variance'></a>
## Boosting and the Bias-Variance Trade-Off

---

Recall that **bagging aims to reduce variance**.

**Boosting aims to reduce bias** (and can reduce variance a bit as well)!

### Why?

The rationale/theory behind boosting is to combine **many weak learners into a single strong learner.**

Instead of using deep/full decision trees like in bagging, **boosting uses shallow/high-bias base estimators.**

Thus, each weak learner has:

- Low variance.
- High bias.

It uses iterative fitting to explain error/misclassification unexplained by the previous base models and reduces bias without increasing variance.

<a id='adaboost'></a>
## AdaBoost

---

AdaBoost is the original boosting algorithm. Predictions from AdaBoost follow this formula:


### $$ AdaBoost(X) = sign\left(\sum_{t=1}^T\alpha_t h_t(X)\right) $$

Where:

$AdaBoost(X)$ is the classification predictions for $y$ using predictor matrix $X$.

$T$ is the set of "weak learners.”

$\alpha_t$ is the contribution weight for weak learner $t$.

$h_t(X)$ is the prediction of weak learner $t$.

$y$ is binary **with values of negative one and one.*

The core principle of AdaBoost is to **fit a sequence of weak learners** (i.e., models that are only slightly better than random guessing, such as a single-split tree) **on repeatedly modified versions of the data**. After each fit, the importance weights on each observation need to be updated. 

The predictions are then combined through a weighted majority vote (or sum) to produce the final prediction. AdaBoost, like all boosting ensemble methods, focuses the next model's fit on the misclassifications/weaknesses of the prior models.

All training examples start with equal importance weighting. When we finish training a classifier, we update the importance weighting of the classifier itself, represented by alpha $\alpha$:

### $$ \alpha_t = \frac{1}{2}ln \left(\frac{1-\epsilon_t}{\epsilon_t}\right) \text{where } \epsilon_t < 1$$

Where $\epsilon_t$ is the misclassification rate for the current classifier:

### $$ \epsilon_t = \frac{\text{misclassifications}_t}{\text{observations}_t} $$

As iterations continue, **examples that are difficult to predict receive ever-increasing influence**. Each subsequent weak learner is thereby forced to concentrate on the examples that are missed by the previous ones in the sequence.

<a id='ex-weights'></a>
### Training Example Weights

AdaBoost sets up a weight vector on the observations, denoted as $D_t$ where $t$ is the current model iteration. $D_t$ is a probability distribution that determines how likely it is that a given observation will be selected as part of the training set for the current estimator.

The $\alpha$ weighting of the last-fit estimator is used in the equation for the weighting distribution. The update equation is:

### $$ D_{t+1}(i) = D_t(i) e^{-\alpha_t y_i h_t(x_i)} $$

Where $i$ is the vector of observation indices and $x_i$ is the observation at the index, $y_i$ is the target.

$h_t$ is the previous model fit in the boosting chain.

Lastly, we'll divide the weights by the sum of weights to normalize them, ensuring that they sum to one and form a probability distribution:

### $$ D_{t+1}(i) = \frac{D_{t+1}(i)}{\sum_{i=1}^N D_{t+1}(i)}$$

<a id='adaboost-viz'></a>
## AdaBoost Visualization

![boostvsbag](./images/adaboost-viz.png)

<a id='gradient'></a>
## Gradient Boosting Models

---

Gradient boosting classifiers are a generalization of boosting to arbitrary, differentiable loss functions. The intuition behind this mechanism is to:

1. Fit a model $F$ to the data.
2. Look at the difference between our observed $y$ and our model $F$. (The $y_i - F(x_i)$ can be thought of as residuals!)
3. Fit a second model, $F_2$, to (roughly) the residuals $y_i - F(x_i)$.
4. Aggregate your model $F$ and $F_2$. While we won't get into the details now, we can interpret residuals as negative gradients. By doing this, we can apply our gradient descent algorithm to optimize our loss and generalize this to many loss functions.

GBRT is an accurate and effective off-the-shelf procedure that can be used for both regression and classification problems. Gradient tree boosting models are used in a variety of areas, including web search ranking and ecology.

[This presentation](http://www.ccs.neu.edu/home/vip/teach/MLcourse/4_boosting/slides/gradient_boosting.pdf) shows a visual example of AdaBoost at work and how AdaBoost laid the groundwork for gradient boosting classifiers.

**The advantages of GBRT are:**

- Natural handling of mixed data types (= heterogeneous features).
- Predictive power.
- Robustness to outliers in output space (via robust loss functions).

**The disadvantages of GBRT are:**
- Scalability: Due to the sequential nature of boosting, it can hardly be parallelized.
- Difficult hyperparameters to tune.


> _For more detailed explanations, see [here](https://www.quora.com/What-is-an-intuitive-explanation-of-Gradient-Boosting) and [here](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3885826/)._

<a id='gboost-viz'></a>
## Gradient Boosting Visualization
![boostvsbag](./images/gboost-viz.png)

<a id='the-difference-between-the-adaboost-and-gradient-boosting'></a>
## The Difference Between the AdaBoost and Gradient Boosting

---


- AdaBoost is about reweighting the preceding model's errors in subsequent iterations.
- Gradient boosting is about fitting subsequent models to the residuals of the last model.

## Playground

---

Let's practice boosting in `sklearn`.

In [3]:
from sklearn.ensemble import BaggingClassifier, BaggingRegressor, AdaBoostRegressor, GradientBoostingRegressor

In [110]:
ada = AdaBoostRegressor(max_depth = 3, n_estimators=100)
gboost = GradientBoostingRegressor(n_estimators=100)

TypeError: __init__() got an unexpected keyword argument 'max_depth'

In [111]:
ada_tree = AdaBoostRegressor(DecisionTreeRegressor(max_depth = 5), n_estimators = 100)

In [5]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from sklearn.datasets import fetch_openml

survey = fetch_openml(data_id=534, as_frame=True)

In [7]:
X = survey.data[survey.feature_names]
X.describe(include="all")

,EDUCATION,SOUTH,SEX,EXPERIENCE,UNION,AGE,RACE,OCCUPATION,SECTOR,MARR
count,534.000000,534,534,534.000000,534,534.000000,534,534,534,534
unique,NaN,2,2,NaN,2,NaN,3,6,3,2
top,NaN,no,male,NaN,not_member,NaN,White,Other,Other,Married
freq,NaN,378,289,NaN,438,NaN,440,156,411,350
mean,13.018727,NaN,NaN,17.822097,NaN,36.833333,NaN,NaN,NaN,NaN
std,2.615373,NaN,NaN,12.379710,NaN,11.726573,NaN,NaN,NaN,NaN
min,2.000000,NaN,NaN,0.000000,NaN,18.000000,NaN,NaN,NaN,NaN
25%,12.000000,NaN,NaN,8.000000,NaN,28.000000,NaN,NaN,NaN,NaN
50%,12.000000,NaN,NaN,15.000000,NaN,35.000000,NaN,NaN,NaN,NaN
75%,15.000000,NaN,NaN,26.000000,NaN,44.000000,NaN,NaN,NaN,NaN
max,18.000000,NaN,NaN,55.000000,NaN,64.000000,NaN,NaN,NaN,NaN

In [8]:
y = survey.target.values.ravel()
survey.target.head()

0    5.10
1    4.95
2    6.67
3    4.00
4    7.50
Name: WAGE, dtype: float64

In [9]:
X.head()

,EDUCATION,SOUTH,SEX,EXPERIENCE,UNION,AGE,RACE,OCCUPATION,SECTOR,MARR
0,8.0,no,female,21.0,not_member,35.0,Hispanic,Other,Manufacturing,Married
1,9.0,no,female,42.0,not_member,57.0,White,Other,Manufacturing,Married
2,12.0,no,male,1.0,not_member,19.0,White,Other,Manufacturing,Unmarried
3,12.0,no,male,4.0,not_member,22.0,White,Other,Other,Unmarried
4,12.0,no,male,17.0,not_member,35.0,White,Other,Other,Married

In [36]:
y -= y.mean()

In [37]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EDUCATION   534 non-null    float64
 1   SOUTH       534 non-null    category
 2   SEX         534 non-null    category
 3   EXPERIENCE  534 non-null    float64
 4   UNION       534 non-null    category
 5   AGE         534 non-null    float64
 6   RACE        534 non-null    category
 7   OCCUPATION  534 non-null    category
 8   SECTOR      534 non-null    category
 9   MARR        534 non-null    category
dtypes: category(7), float64(3)
memory usage: 17.1 KB

In [38]:
#clean up X make sure no missing values and all numeric for a regressor
clean_df = pd.get_dummies(X, drop_first=True)

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
#train/test split
X_train, X_test, y_train, y_test = train_test_split(clean_df, y, random_state = 22)

In [48]:
ada = AdaBoostRegressor(n_estimators=100, random_state = 22)
gboost = GradientBoostingRegressor(n_estimators=100, random_state = 22)

In [49]:
ada.fit(X_train, y_train)

AdaBoostRegressor(n_estimators=100, random_state=22)

In [50]:
ada.score(X_train, y_train)

0.39573531923759875

In [51]:
ada.score(X_test, y_test)

0.09811505401522058

In [52]:
gboost.fit(X_train, y_train)

GradientBoostingRegressor(random_state=22)

In [53]:
gboost.score(X_train, y_train)

0.7040262523591478

In [54]:
gboost.score(X_test, y_test)

-0.32651576444179686

In [55]:
from sklearn.tree import DecisionTreeRegressor

In [72]:
tree = DecisionTreeRegressor(max_depth = 1)

In [73]:
tree.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1)

In [74]:
tree.score(X_train, y_train)

0.1386434063918094

In [75]:
tree.score(X_test, y_test)

0.2039138310736749

In [76]:
bag = BaggingRegressor()

In [77]:
bag.fit(X_train, y_train)

BaggingRegressor()

In [78]:
bag.score(X_test, y_test)

-0.6562762890941773

In [79]:
from sklearn.model_selection import GridSearchCV

In [80]:
boost = AdaBoostRegressor()

In [86]:
params = {'n_estimators': [10, 50],
         'learning_rate': [1.0, 0.1, 0.01, 0.05],
         'loss': ['linear', 'squared', 'exponential'] }

In [87]:
grid = GridSearchCV(boost, param_grid=params)

In [88]:
grid.fit(X_train, y_train)

GridSearchCV(estimator=AdaBoostRegressor(),
             param_grid={'learning_rate': [1.0, 0.1, 0.01, 0.05],
                         'loss': ['linear', 'exponential'],
                         'n_estimators': [10, 50]})

In [89]:
grid.best_params_

{'learning_rate': 0.05, 'loss': 'exponential', 'n_estimators': 50}

In [90]:
grid.score(X_test, y_test)

0.2538203895603246

In [91]:
grid.score(X_train, y_train)

0.3996622975441546

In [92]:
gboost = GradientBoostingRegressor()

In [99]:
params = {'loss': ['ls', 'huber'],
         'learning_rate': [0.1, 0.05, 0.01, 0.4], 
         'n_estimators': [10, 50, 100]}

In [100]:
boost_grid = GridSearchCV(gboost, param_grid=params)

In [101]:
boost_grid.fit(X_train, y_train)

GridSearchCV(estimator=GradientBoostingRegressor(),
             param_grid={'learning_rate': [0.1, 0.05, 0.01, 0.4],
                         'loss': ['ls', 'huber'],
                         'n_estimators': [10, 50, 100]})

In [102]:
boost_grid.best_params_

{'learning_rate': 0.05, 'loss': 'ls', 'n_estimators': 50}

In [103]:
boost_grid.score(X_train, y_train)

0.515212216853631

In [104]:
boost_grid.score(X_test, y_test)

-0.020254621191575506

In [105]:
best_ada = grid.best_estimator_

In [107]:
ada_df = pd.DataFrame({'features': clean_df.columns, 'importance': best_ada.feature_importances_})

In [108]:
ada_df.sort_values('importance', ascending = False)

                   features  importance
0                 EDUCATION    0.361714
2                       AGE    0.223376
8     OCCUPATION_Management    0.112792
1                EXPERIENCE    0.110002
4                  SEX_male    0.075323
5          UNION_not_member    0.023730
3                 SOUTH_yes    0.022205
10  OCCUPATION_Professional    0.022073
12       OCCUPATION_Service    0.021375
7                RACE_White    0.009811
15           MARR_Unmarried    0.006621
14             SECTOR_Other    0.004062
11         OCCUPATION_Sales    0.003296
13     SECTOR_Manufacturing    0.002085
9          OCCUPATION_Other    0.001433
6                RACE_Other    0.000103

<a id='resources'></a>

## Additional Resources

---

- [Random Forest on Wikipedia](https://en.wikipedia.org/wiki/Random_forest)
- [Quora Question on Random Forests](https://www.quora.com/How-does-randomization-in-a-random-forest-work?redirected_qid=212859)
- [Scikit-Learn Ensemble Methods](http://scikit-learn.org/stable/modules/ensemble.html)
- [Scikit-Learn Random Forest Classifiers](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)
- [Academic Introduction to Adaptive Boosting](http://rob.schapire.net/papers/explaining-adaboost.pdf)
- [Stack Exchange AdaBoost vs. Gradient Boosting](http://stats.stackexchange.com/questions/164233/intuitive-explanations-of-differences-between-gradient-boosting-trees-gbm-ad)
- [A Gentle Introduction to Gradient Boosting](http://www.ccs.neu.edu/home/vip/teach/MLcourse/4_boosting/slides/gradient_boosting.pdf)
- [Quora on Intuitive Explanations of AdaBoost](https://www.quora.com/What-is-AdaBoost)
- MIT on [Adaptive Boosting](http://math.mit.edu/~rothvoss/18.304.3PM/Presentations/1-Eric-Boosting304FinalRpdf.pdf)
- A Lighter [Math Introduction](http://www.ccs.neu.edu/home/vip/teach/MLcourse/4_boosting/slides/gradient_boosting.pdf) to AdaBoosting and Gradient Boosting (h/t Charlie)
- A [Walk Through](https://www.analyticsvidhya.com/blog/2016/02/complete-guide-parameter-tuning-gradient-boosting-gbm-python/) on Tuning Gradient Boosting Models (h/t Sheena)