### Boosted Ensembles 

Continuing on with our work with classifiers and ensembles today we introduce boosted models, a powerful collection of tree based models that learn in sequence.

In [99]:
# !pip install xgboost

In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split

### Gradient Boosted Models

![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Ensemble_Boosting.svg/2880px-Ensemble_Boosting.svg.png)

In [101]:
from sklearn.ensemble import HistGradientBoostingClassifier
from xgboost import XGBClassifier

In [103]:
cancer = load_breast_cancer(as_frame=True).frame

In [105]:
X_train, X_test, y_train, y_test = train_test_split(cancer.drop(columns = 'target'), cancer['target'])

### Comparing Boosted Models

Returning to the food marketing data from last class, how does a boosted model perform?  Is this worth using in targeting customers and what do you think is driving responses to the advertisement?

In [96]:
food_marketing = pd.read_csv('https://raw.githubusercontent.com/jfkoehler/nyu_bootcamp_fa25/refs/heads/main/data/food_data.csv')

In [98]:
food_marketing.head()

     ID  Year_Birth   Education  ... Z_CostContact  Z_Revenue  Response
0  5524        1957  Graduation  ...             3         11         1
1  2174        1954  Graduation  ...             3         11         0
2  4141        1965  Graduation  ...             3         11         0
3  6182        1984  Graduation  ...             3         11         0
4  5324        1981         PhD  ...             3         11         0

[5 rows x 29 columns]

### Inspecting Results

- [Partial Dependence Plots](https://scikit-learn.org/stable/modules/partial_dependence.html)
- [Permutation Feature Importance](https://scikit-learn.org/stable/modules/permutation_importance.html)

In [102]:
from sklearn.inspection import PartialDependenceDisplay, permutation_importance

#### PROBLEM

Below, a dataset around an email campaign for sales is loaded and displayed.  Explore the description of the task [here](https://blog.minethatdata.com/2008/03/minethatdata-e-mail-analytics-and-data.html).  Consider a strategy for model building and evaluation.

In [62]:
# !pip install scikit-uplift

In [63]:
from sklift.datasets import fetch_hillstrom

In [64]:
dataset = fetch_hillstrom(target_col='conversion')
data, target, treatment = dataset.data, dataset.target, dataset.treatment

In [59]:
data.head()

   recency history_segment  history  mens  womens   zip_code  newbie channel
0       10  2) $100 - $200   142.44     1       0  Surburban       0   Phone
1        6  3) $200 - $350   329.08     1       1      Rural       1     Web
2        7  2) $100 - $200   180.65     0       1  Surburban       1     Web
3        9  5) $500 - $750   675.83     1       0      Rural       1     Web
4        2    1) $0 - $100    45.34     1       0      Urban       0     Web

In [60]:
target.head()

0    0
1    0
2    0
3    0
4    0
Name: conversion, dtype: int64

In [61]:
treatment.head()

0    Womens E-Mail
1        No E-Mail
2    Womens E-Mail
3      Mens E-Mail
4    Womens E-Mail
Name: segment, dtype: object